apiVersion: v1
kind: Service
metadata:
  name: cache-runtime
  namespace: mailium
spec:
  type: ClusterIP
  selector:
    app: cache-runtime
  ports:
    - name: http
      port: 5001
      targetPort: http
